version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: infrastructure/aws/codedeploy/install_dependencies
      timeout: 300
      runas: root
    - location: infrastructure/aws/codedeploy/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: infrastructure/aws/codedeploy/stop_server
      timeout: 300
      runas: root
