version: 0.2

env:
  variables:
    BUCKET: "s3://diego-aws-workshop"
    FRONTEND_DIR: "frontend"
    BUILD_DIR: "build"
    REACT_APP_USE_OWN_API: "true"
    REACT_APP_API_DOMAIN: "http://api_url.com"

phases:
  pre_build:
    commands:
      - echo "Installing npm dependencies ..."
      - cd "$FRONTEND_DIR"
      - echo "cwd: `pwd`"
      - npm install
  build:
    commands:
      - echo "cwd: `pwd`"
      - echo "Build started on `date`"
      - echo "Building ..."
      - npm run build
  post_build:
    commands:
      - echo "cwd: `pwd`"
      - echo "Uploading build to $BUCKET ..."
      - aws s3 sync --delete "$BUILD_DIR" "$BUCKET"
      - echo "Build completed on `date`"
