version: 0.2

env:
  variables:
    BUCKET_PARAMETER_NAME: "/prod/codebuild/WEBSITE_BUCKET_NAME"
    FRONTEND_DIR: "frontend"
    BUILD_DIR: "build"
    REACT_APP_USE_OWN_API: "true"
    REACT_APP_API_DOMAIN: "http://api_url.com"

phases:
  pre_build:
    commands:
      - echo "Installing npm dependencies and jq..."
      - cd "$FRONTEND_DIR"
      - npm install
      - apt-get update
      - apt install jq
      - pip install --upgrade awscli
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Building ..."
      - npm run build
  post_build:
    commands:
      - aws --version
      - echo "Uploading build to $BUCKET ..."
      - export BUCKET=`aws ssm get-parameter --name "$BUCKET_PARAMETER_NAME" --region us-east-1 | jq .Parameter.Value`
      - echo "check variables..."
      - echo $BUILD_DIR
      - echo $BUCKET
      - aws s3 sync "$BUILD_DIR" "$BUCKET" --delete
      - echo "Build completed on `date`"
